name: Read Secret

on:
  workflow_dispatch:

jobs:
  reveal-secret:
    runs-on: ubuntu-latest
    steps:
      - name: Echo or Save Secret
        env:
          JKS_SECRET: ${{ secrets.BANDORI_JKS }}
        run: |
          # 如果是 Base64 文本，可还原并保存为文件
          echo "$JKS_SECRET" | base64 -d > decoded_keystore.jks

      - name: Upload JKS as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: my-jks-file
          path: decoded_keystore.jks